from functools import lru_cache
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        protected_namespaces=(),
    )

    app_name: str = "SEO-AD AutoPilot"
    environment: str = Field(default="development", alias="SEO_AD_BOT_ENVIRONMENT")
    api_key: str = Field(default="dev-key", alias="SEO_AD_BOT_API_KEY")
    default_workspace: str = Field(default="demo-pack", alias="SEO_AD_BOT_DEFAULT_WORKSPACE")
    database_url: str = Field(
        default="sqlite:///./var/seo-ad-autopilot.db",
        alias="DATABASE_URL",
    )
    require_postgres: bool = Field(default=False, alias="SEO_AD_BOT_REQUIRE_POSTGRES")
    disable_sqlite_fallback: bool = Field(default=False, alias="SEO_AD_BOT_DISABLE_SQLITE_FALLBACK")
    redis_url: str = Field(default="redis://localhost:6379/0", alias="REDIS_URL")
    skill_registry_path: Path = Field(
        default=Path("packages/skill-registry/registry.json"),
        alias="SEO_AD_BOT_SKILL_REGISTRY_PATH",
    )
    web_origin: str = Field(default="http://127.0.0.1:3000", alias="SEO_AD_BOT_WEB_ORIGIN")
    api_public_base_url: str = Field(default="http://127.0.0.1:8000", alias="SEO_AD_BOT_API_PUBLIC_BASE_URL")
    next_app_url: str = Field(
        default="http://127.0.0.1:3000",
        alias="SEO_AD_BOT_NEXT_APP_URL",
    )
    state_dir: Path = Field(default=Path("var"), alias="SEO_AD_BOT_STATE_DIR")
    auto_deploy_enabled: bool = Field(default=True, alias="SEO_AD_BOT_AUTO_DEPLOY_ENABLED")
    approval_required_threshold: int = Field(default=60, alias="SEO_AD_BOT_APPROVAL_REQUIRED_THRESHOLD")
    block_auto_deploy_threshold: int = Field(default=80, alias="SEO_AD_BOT_BLOCK_AUTO_DEPLOY_THRESHOLD")
    monitor_window_minutes: int = Field(default=90, alias="SEO_AD_BOT_MONITOR_WINDOW_MINUTES")
    rollback_window_minutes: int = Field(default=5, alias="SEO_AD_BOT_ROLLBACK_WINDOW_MINUTES")
    auto_cruise_enabled: bool = Field(default=False, alias="SEO_AD_BOT_AUTO_CRUISE_ENABLED")
    strict_providers: bool = Field(default=False, alias="SEO_AD_BOT_STRICT_PROVIDERS")
    provider_evidence_freshness_minutes: int = Field(default=1440, alias="SEO_AD_BOT_PROVIDER_EVIDENCE_FRESHNESS_MINUTES")
    enable_browser_crawl: bool = Field(default=False, alias="SEO_AD_BOT_ENABLE_BROWSER_CRAWL")
    browser_crawl_antibot_cooldown_minutes: int = Field(
        default=30,
        alias="SEO_AD_BOT_BROWSER_CRAWL_ANTI_BOT_COOLDOWN_MINUTES",
    )
    browser_crawl_antibot_cooldown_max_minutes: int = Field(
        default=180,
        alias="SEO_AD_BOT_BROWSER_CRAWL_ANTI_BOT_COOLDOWN_MAX_MINUTES",
    )
    playwright_provider_url: str = Field(default="", alias="SEO_AD_BOT_PLAYWRIGHT_PROVIDER_URL")
    playwright_access_token: str = Field(default="", alias="SEO_AD_BOT_PLAYWRIGHT_ACCESS_TOKEN")
    playwright_credentials_json: str = Field(default="", alias="SEO_AD_BOT_PLAYWRIGHT_CREDENTIALS_JSON")
    playwright_service_account_json: str = Field(default="", alias="SEO_AD_BOT_PLAYWRIGHT_SERVICE_ACCOUNT_JSON")
    playwright_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_PLAYWRIGHT_AUTH_HEADER")
    playwright_provider_timeout_ms: int = Field(default=12000, alias="SEO_AD_BOT_PLAYWRIGHT_PROVIDER_TIMEOUT_MS")
    trend_provider_url: str = Field(default="", alias="SEO_AD_BOT_TREND_PROVIDER_URL")
    news_provider_url: str = Field(default="", alias="SEO_AD_BOT_NEWS_PROVIDER_URL")
    qa_provider_url: str = Field(default="", alias="SEO_AD_BOT_QA_PROVIDER_URL")
    market_provider_access_token: str = Field(default="", alias="SEO_AD_BOT_MARKET_PROVIDER_ACCESS_TOKEN")
    market_provider_credentials_json: str = Field(default="", alias="SEO_AD_BOT_MARKET_PROVIDER_CREDENTIALS_JSON")
    market_provider_service_account_json: str = Field(default="", alias="SEO_AD_BOT_MARKET_PROVIDER_SERVICE_ACCOUNT_JSON")
    trend_provider_access_token: str = Field(default="", alias="SEO_AD_BOT_TREND_PROVIDER_ACCESS_TOKEN")
    trend_provider_credentials_json: str = Field(default="", alias="SEO_AD_BOT_TREND_PROVIDER_CREDENTIALS_JSON")
    trend_provider_service_account_json: str = Field(default="", alias="SEO_AD_BOT_TREND_PROVIDER_SERVICE_ACCOUNT_JSON")
    news_provider_access_token: str = Field(default="", alias="SEO_AD_BOT_NEWS_PROVIDER_ACCESS_TOKEN")
    news_provider_credentials_json: str = Field(default="", alias="SEO_AD_BOT_NEWS_PROVIDER_CREDENTIALS_JSON")
    news_provider_service_account_json: str = Field(default="", alias="SEO_AD_BOT_NEWS_PROVIDER_SERVICE_ACCOUNT_JSON")
    qa_provider_access_token: str = Field(default="", alias="SEO_AD_BOT_QA_PROVIDER_ACCESS_TOKEN")
    qa_provider_credentials_json: str = Field(default="", alias="SEO_AD_BOT_QA_PROVIDER_CREDENTIALS_JSON")
    qa_provider_service_account_json: str = Field(default="", alias="SEO_AD_BOT_QA_PROVIDER_SERVICE_ACCOUNT_JSON")
    market_provider_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_MARKET_PROVIDER_TIMEOUT_MS")
    cms_provider_url: str = Field(default="", alias="SEO_AD_BOT_CMS_PROVIDER_URL")
    sitemap_provider_url: str = Field(default="", alias="SEO_AD_BOT_SITEMAP_PROVIDER_URL")
    sitemap_provider_access_token: str = Field(default="", alias="SEO_AD_BOT_SITEMAP_ACCESS_TOKEN")
    sitemap_provider_credentials_json: str = Field(default="", alias="SEO_AD_BOT_SITEMAP_CREDENTIALS_JSON")
    sitemap_provider_service_account_json: str = Field(default="", alias="SEO_AD_BOT_SITEMAP_SERVICE_ACCOUNT_JSON")
    sitemap_provider_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_SITEMAP_AUTH_HEADER")
    sitemap_provider_timeout_ms: int = Field(default=6000, alias="SEO_AD_BOT_SITEMAP_PROVIDER_TIMEOUT_MS")
    script_provider_url: str = Field(default="", alias="SEO_AD_BOT_SCRIPT_PROVIDER_URL")
    script_access_token: str = Field(default="", alias="SEO_AD_BOT_SCRIPT_ACCESS_TOKEN")
    static_export_provider_url: str = Field(default="", alias="SEO_AD_BOT_STATIC_EXPORT_PROVIDER_URL")
    static_export_provider_urls: str = Field(default="", alias="SEO_AD_BOT_STATIC_EXPORT_PROVIDER_URLS")
    static_export_access_token: str = Field(default="", alias="SEO_AD_BOT_STATIC_EXPORT_ACCESS_TOKEN")
    ad_network_provider_url: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_PROVIDER_URL")
    ad_network_provider_urls: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_PROVIDER_URLS")
    ad_network_access_token: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_ACCESS_TOKEN")
    ad_network_credentials_json: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_CREDENTIALS_JSON")
    ad_network_service_account_json: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_SERVICE_ACCOUNT_JSON")
    ad_network_account_id: str = Field(default="", alias="SEO_AD_BOT_AD_NETWORK_ACCOUNT_ID")
    ad_network_provider_family: str = Field(default="generic", alias="SEO_AD_BOT_AD_NETWORK_PROVIDER_FAMILY")
    ad_network_currency: str = Field(default="USD", alias="SEO_AD_BOT_AD_NETWORK_CURRENCY")
    ad_network_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_AD_NETWORK_AUTH_HEADER")
    ad_network_provider_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_AD_NETWORK_PROVIDER_TIMEOUT_MS")
    billing_gateway_url: str = Field(default="", alias="SEO_AD_BOT_BILLING_GATEWAY_URL")
    queue_backend: str = Field(default="memory", alias="SEO_AD_BOT_QUEUE_BACKEND")
    queue_retry_limit: int = Field(default=1, alias="SEO_AD_BOT_QUEUE_RETRY_LIMIT")
    queue_retry_backoff_seconds: int = Field(default=30, alias="SEO_AD_BOT_QUEUE_RETRY_BACKOFF_SECONDS")
    queue_retry_backoff_max_seconds: int = Field(default=300, alias="SEO_AD_BOT_QUEUE_RETRY_BACKOFF_MAX_SECONDS")
    worker_state_file: str = Field(default="", alias="SEO_AD_BOT_WORKER_STATE_FILE")
    artifact_store_backend: str = Field(default="local", alias="SEO_AD_BOT_ARTIFACT_STORE_BACKEND")
    artifact_store_http_base_url: str = Field(default="", alias="SEO_AD_BOT_ARTIFACT_STORE_HTTP_BASE_URL")
    artifact_store_http_token: str = Field(default="", alias="SEO_AD_BOT_ARTIFACT_STORE_HTTP_TOKEN")
    artifact_store_http_timeout_ms: int = Field(default=4000, alias="SEO_AD_BOT_ARTIFACT_STORE_HTTP_TIMEOUT_MS")
    billing_gateway_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_BILLING_GATEWAY_TIMEOUT_MS")
    enable_otlp: bool = Field(default=False, alias="SEO_AD_BOT_ENABLE_OTLP")
    otlp_endpoint: str = Field(default="", alias="SEO_AD_BOT_OTLP_ENDPOINT")
    otlp_headers: str = Field(default="", alias="SEO_AD_BOT_OTLP_HEADERS")
    otlp_timeout_ms: int = Field(default=10000, alias="SEO_AD_BOT_OTLP_TIMEOUT_MS")
    otlp_insecure: bool = Field(default=False, alias="SEO_AD_BOT_OTLP_INSECURE")
    observability_strict: bool = Field(default=False, alias="SEO_AD_BOT_OBSERVABILITY_STRICT")
    sentry_dsn: str = Field(default="", alias="SEO_AD_BOT_SENTRY_DSN")
    enable_visual_screenshots: bool = Field(default=False, alias="SEO_AD_BOT_ENABLE_VISUAL_SCREENSHOTS")
    visual_farm_endpoint: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_ENDPOINT")
    visual_farm_endpoints: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_ENDPOINTS")
    visual_farm_access_token: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_ACCESS_TOKEN")
    visual_farm_credentials_json: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_CREDENTIALS_JSON")
    visual_farm_service_account_json: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_SERVICE_ACCOUNT_JSON")
    visual_farm_timeout_ms: int = Field(default=12000, alias="SEO_AD_BOT_VISUAL_FARM_TIMEOUT_MS")
    visual_farm_strict: bool = Field(default=False, alias="SEO_AD_BOT_VISUAL_FARM_STRICT")
    visual_farm_probe_freshness_minutes: int = Field(default=30, alias="SEO_AD_BOT_VISUAL_FARM_PROBE_FRESHNESS_MINUTES")
    visual_farm_gateway_url: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_GATEWAY_URL")
    visual_farm_gateway_urls: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_GATEWAY_URLS")
    visual_farm_gateway_access_token: str = Field(default="", alias="SEO_AD_BOT_VISUAL_FARM_GATEWAY_ACCESS_TOKEN")
    visual_farm_gateway_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_VISUAL_FARM_GATEWAY_AUTH_HEADER")
    visual_farm_gateway_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_VISUAL_FARM_GATEWAY_TIMEOUT_MS")
    model_gateway_url: str = Field(default="", alias="SEO_AD_BOT_MODEL_GATEWAY_URL")
    model_gateway_urls: str = Field(default="", alias="SEO_AD_BOT_MODEL_GATEWAY_URLS")
    model_gateway_access_token: str = Field(default="", alias="SEO_AD_BOT_MODEL_GATEWAY_ACCESS_TOKEN")
    model_gateway_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_MODEL_GATEWAY_AUTH_HEADER")
    model_gateway_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_MODEL_GATEWAY_TIMEOUT_MS")
    runtime_edge_gateway_url: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_EDGE_GATEWAY_URL")
    runtime_edge_gateway_urls: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_EDGE_GATEWAY_URLS")
    runtime_edge_gateway_access_token: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_EDGE_GATEWAY_ACCESS_TOKEN")
    runtime_edge_gateway_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_RUNTIME_EDGE_GATEWAY_AUTH_HEADER")
    runtime_edge_gateway_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_RUNTIME_EDGE_GATEWAY_TIMEOUT_MS")
    runtime_ingress_gateway_url: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_INGRESS_GATEWAY_URL")
    runtime_ingress_gateway_urls: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_INGRESS_GATEWAY_URLS")
    runtime_ingress_gateway_access_token: str = Field(default="", alias="SEO_AD_BOT_RUNTIME_INGRESS_GATEWAY_ACCESS_TOKEN")
    runtime_ingress_gateway_auth_header: str = Field(default="Authorization", alias="SEO_AD_BOT_RUNTIME_INGRESS_GATEWAY_AUTH_HEADER")
    runtime_ingress_gateway_timeout_ms: int = Field(default=8000, alias="SEO_AD_BOT_RUNTIME_INGRESS_GATEWAY_TIMEOUT_MS")
    alert_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_WEBHOOK_URL")
    alert_webhook_urls: str = Field(default="", alias="SEO_AD_BOT_ALERT_WEBHOOK_URLS")
    alert_blocking_webhook_urls: str = Field(default="", alias="SEO_AD_BOT_ALERT_BLOCKING_WEBHOOK_URLS")
    alert_recoverable_webhook_urls: str = Field(default="", alias="SEO_AD_BOT_ALERT_RECOVERABLE_WEBHOOK_URLS")
    alert_webhook_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_WEBHOOK_TOKEN")
    alert_webhook_timeout_ms: int = Field(default=3000, alias="SEO_AD_BOT_ALERT_WEBHOOK_TIMEOUT_MS")
    alert_emit_cooldown_seconds: int = Field(default=0, alias="SEO_AD_BOT_ALERT_EMIT_COOLDOWN_SECONDS")
    alert_pagerduty_routing_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_PAGERDUTY_ROUTING_KEY")
    alert_pagerduty_endpoint: str = Field(default="https://events.pagerduty.com/v2/enqueue", alias="SEO_AD_BOT_ALERT_PAGERDUTY_ENDPOINT")
    alert_pagerduty_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_PAGERDUTY_SOURCE")
    alert_opsgenie_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_OPSGENIE_API_KEY")
    alert_opsgenie_endpoint: str = Field(default="https://api.opsgenie.com/v2/alerts", alias="SEO_AD_BOT_ALERT_OPSGENIE_ENDPOINT")
    alert_opsgenie_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_OPSGENIE_SOURCE")
    alert_splunk_oncall_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_SPLUNK_ONCALL_API_KEY")
    alert_splunk_oncall_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_SPLUNK_ONCALL_ENDPOINT")
    alert_splunk_oncall_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_SPLUNK_ONCALL_SOURCE")
    alert_grafana_oncall_integration_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_GRAFANA_ONCALL_INTEGRATION_KEY")
    alert_grafana_oncall_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_GRAFANA_ONCALL_ENDPOINT")
    alert_grafana_oncall_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_GRAFANA_ONCALL_SOURCE")
    alert_feishu_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_FEISHU_WEBHOOK_URL")
    alert_feishu_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_FEISHU_SOURCE")
    alert_dingtalk_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_DINGTALK_WEBHOOK_URL")
    alert_dingtalk_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_DINGTALK_SOURCE")
    alert_wecom_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_WECOM_WEBHOOK_URL")
    alert_wecom_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_WECOM_SOURCE")
    alert_google_chat_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_GOOGLE_CHAT_WEBHOOK_URL")
    alert_google_chat_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_GOOGLE_CHAT_SOURCE")
    alert_discord_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_DISCORD_WEBHOOK_URL")
    alert_discord_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_DISCORD_SOURCE")
    alert_slack_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_SLACK_WEBHOOK_URL")
    alert_slack_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_SLACK_SOURCE")
    alert_teams_webhook_url: str = Field(default="", alias="SEO_AD_BOT_ALERT_TEAMS_WEBHOOK_URL")
    alert_teams_source: str = Field(default="seo-ad-autopilot", alias="SEO_AD_BOT_ALERT_TEAMS_SOURCE")
    alert_jira_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_JIRA_ENDPOINT")
    alert_jira_project_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_JIRA_PROJECT_KEY")
    alert_jira_email: str = Field(default="", alias="SEO_AD_BOT_ALERT_JIRA_EMAIL")
    alert_jira_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_JIRA_API_TOKEN")
    alert_linear_endpoint: str = Field(default="https://api.linear.app/graphql", alias="SEO_AD_BOT_ALERT_LINEAR_ENDPOINT")
    alert_linear_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_LINEAR_API_KEY")
    alert_linear_team_id: str = Field(default="", alias="SEO_AD_BOT_ALERT_LINEAR_TEAM_ID")
    alert_asana_endpoint: str = Field(default="https://app.asana.com/api/1.0/tasks", alias="SEO_AD_BOT_ALERT_ASANA_ENDPOINT")
    alert_asana_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_ASANA_API_TOKEN")
    alert_asana_project_gid: str = Field(default="", alias="SEO_AD_BOT_ALERT_ASANA_PROJECT_GID")
    alert_manageengine_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_MANAGEENGINE_ENDPOINT")
    alert_manageengine_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_MANAGEENGINE_API_KEY")
    alert_bmc_helix_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_BMC_HELIX_ENDPOINT")
    alert_bmc_helix_username: str = Field(default="", alias="SEO_AD_BOT_ALERT_BMC_HELIX_USERNAME")
    alert_bmc_helix_password: str = Field(default="", alias="SEO_AD_BOT_ALERT_BMC_HELIX_PASSWORD")
    alert_monday_endpoint: str = Field(default="https://api.monday.com/v2", alias="SEO_AD_BOT_ALERT_MONDAY_ENDPOINT")
    alert_monday_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_MONDAY_API_TOKEN")
    alert_monday_board_id: str = Field(default="", alias="SEO_AD_BOT_ALERT_MONDAY_BOARD_ID")
    alert_clickup_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_CLICKUP_ENDPOINT")
    alert_clickup_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_CLICKUP_API_TOKEN")
    alert_redmine_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_REDMINE_ENDPOINT")
    alert_redmine_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_REDMINE_API_KEY")
    alert_zoho_desk_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZOHO_DESK_ENDPOINT")
    alert_zoho_desk_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZOHO_DESK_API_TOKEN")
    alert_zoho_desk_department_id: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZOHO_DESK_DEPARTMENT_ID")
    alert_gitlab_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_GITLAB_ENDPOINT")
    alert_gitlab_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_GITLAB_API_TOKEN")
    alert_youtrack_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_YOUTRACK_ENDPOINT")
    alert_youtrack_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_YOUTRACK_API_TOKEN")
    alert_youtrack_project_id: str = Field(default="", alias="SEO_AD_BOT_ALERT_YOUTRACK_PROJECT_ID")
    alert_freshdesk_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_FRESHDESK_ENDPOINT")
    alert_freshdesk_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_FRESHDESK_API_KEY")
    alert_intercom_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_INTERCOM_ENDPOINT")
    alert_intercom_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_INTERCOM_API_TOKEN")
    alert_trello_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_TRELLO_ENDPOINT")
    alert_trello_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_TRELLO_KEY")
    alert_trello_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_TRELLO_TOKEN")
    alert_airtable_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_AIRTABLE_ENDPOINT")
    alert_airtable_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_AIRTABLE_API_TOKEN")
    alert_servicenow_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_SERVICENOW_ENDPOINT")
    alert_servicenow_username: str = Field(default="", alias="SEO_AD_BOT_ALERT_SERVICENOW_USERNAME")
    alert_servicenow_password: str = Field(default="", alias="SEO_AD_BOT_ALERT_SERVICENOW_PASSWORD")
    alert_zendesk_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZENDESK_ENDPOINT")
    alert_zendesk_email: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZENDESK_EMAIL")
    alert_zendesk_api_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_ZENDESK_API_TOKEN")
    alert_freshservice_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_FRESHSERVICE_ENDPOINT")
    alert_freshservice_api_key: str = Field(default="", alias="SEO_AD_BOT_ALERT_FRESHSERVICE_API_KEY")
    alert_azure_devops_endpoint: str = Field(default="", alias="SEO_AD_BOT_ALERT_AZURE_DEVOPS_ENDPOINT")
    alert_azure_devops_pat: str = Field(default="", alias="SEO_AD_BOT_ALERT_AZURE_DEVOPS_PAT")
    alert_twilio_account_sid: str = Field(default="", alias="SEO_AD_BOT_ALERT_TWILIO_ACCOUNT_SID")
    alert_twilio_auth_token: str = Field(default="", alias="SEO_AD_BOT_ALERT_TWILIO_AUTH_TOKEN")
    alert_twilio_from_number: str = Field(default="", alias="SEO_AD_BOT_ALERT_TWILIO_FROM_NUMBER")
    alert_twilio_to_numbers: str = Field(default="", alias="SEO_AD_BOT_ALERT_TWILIO_TO_NUMBERS")
    alert_twilio_voice_to_numbers: str = Field(default="", alias="SEO_AD_BOT_ALERT_TWILIO_VOICE_TO_NUMBERS")
    alert_smtp_host: str = Field(default="", alias="SEO_AD_BOT_ALERT_SMTP_HOST")
    alert_smtp_port: int = Field(default=587, alias="SEO_AD_BOT_ALERT_SMTP_PORT")
    alert_smtp_username: str = Field(default="", alias="SEO_AD_BOT_ALERT_SMTP_USERNAME")
    alert_smtp_password: str = Field(default="", alias="SEO_AD_BOT_ALERT_SMTP_PASSWORD")
    alert_smtp_from_address: str = Field(default="", alias="SEO_AD_BOT_ALERT_SMTP_FROM_ADDRESS")
    alert_smtp_to_addresses: str = Field(default="", alias="SEO_AD_BOT_ALERT_SMTP_TO_ADDRESSES")
    alert_smtp_use_tls: bool = Field(default=True, alias="SEO_AD_BOT_ALERT_SMTP_USE_TLS")
    alert_preset_admin_keys: str = Field(default="", alias="SEO_AD_BOT_ALERT_PRESET_ADMIN_KEYS")
    alert_preset_strict_admin: bool = Field(default=False, alias="SEO_AD_BOT_ALERT_PRESET_STRICT_ADMIN")


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
